### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by kylemac** [static-dev/spike-records#2]
for the `url` types (although it likely is a good idea for all types), we should have some kind of `cache: true` where we simply return the data right off the `compiler.options.locals` if it already exists. this will give us a cache so we won't have network overhead for each compile (like if you updated a css file). 

i should note, i didn't look up whether the webpack `run` hook runs every time or just on the first compile, which would make this issue moot.

**Comment by jescalan** [comment]
I just tested this and it only fires off the plugin on the initial compile, it doesn't hit it when watch recompiles. Whoo! So I'll close this one out for now.
