### ISSUE TITLE
Item not being injected into dynamically created views

### ISSUE THREAD

**Issue by mcrider** [static-dev/spike-records#68]
I'm using spike-records to create blog posts dynamically from an API endpoint, but it seems that the 'item' local is not available to my template.  There is a `blog` field in my locals variable that lists all the posts, and the post views are indeed being created in the public/blog/ folder, but can't figure out how to get to the data specific to each post.  Here's my app.js file, am I doing something wrong?  BTW I generated this project yesterday so everything should be brand new.

```
const Records = require('spike-records')
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
const pageId = require('spike-page-id')

const env = process.env.NODE_ENV
const locals = {}

module.exports = {
  devtool: 'source-map',
  matchers: { html: '*(**/)*.sgr', css: '*(**/)*.sss' },
  ignore: ['**/layout.sgr', '**/_*', '**/.*', 'readme.md', 'yarn.lock'],
  reshape: htmlStandards({
    root: './views',
    locals: (ctx) => Object.assign(locals, { pageId: pageId(ctx) }),
    minify: env === 'production'
  }),
  postcss: cssStandards({
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  plugins: [
    new Records({
      addDataTo: locals,
      blog: {
        url: 'URL to API that returns an array of objects',
        template: {
          path: 'views/post.sgr',
          output: (post) => { return `blog/${post.slug}.html` }
        }
      },
    })
  ],
  babel: jsStandards(),
  server: {
    open: false
  }
}
```

**Comment by jescalan** [comment]
Ah I'm sorry this is a bug that I introduced with a recent change. I'll have this patched shortly and update here

**Comment by jescalan** [comment]
Fixed! Sorry for the inconvenience earlier 😢 

https://github.com/static-dev/spike-records/releases/tag/v1.0.3

**Comment by mcrider** [comment]
No problem at all!  Thanks for the fix.

Oh and Spike is seriously awesome..  Fully switched over from Metalsmith for all my new sites.  Its the only SSG with first-class API support (through records) which is so important to me.  Its also the best Buffy character.
