### ISSUE TITLE
A template file find imported/extended file from the project root rather than the file location

### ISSUE THREAD

**Issue by yjcrocks** [static-dev/spike-records#69]
I simply added this plugin to the default spike template and found that the template file is interpreted as if they are in the project root.

**1. Normal `views/papers.sgr` worked correctly as expected.**

```pug
extends(src='layout.sgr')
  block(name='content')
    h2 Simple paper view
    ul
      each(loop='paper of papers')
        li: a(href='/papers/{{ paper.slug }}') {{ paper.title }}
```

**2. When I added new `views/paper.sgr` as a template it prompted an error.**

```pug
extends(src='layout.sgr')
  block(name='content')
    h2 {{ item.title }}
```

The error log was as follow:
```
{ Error: ENOENT: no such file or directory, open 'D:\Users\...\project-root\layout.sgr'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at tree.reduce (D:\Users\...\project-root\node_modules\reshape-layouts\lib\index.js:41:27)
    at Array.reduce (native)
    at handleExtendsNodes (D:\Users\...\project-root\node_modules\reshape-layouts\lib\index.js:26:15)
    at layoutsPlugin (D:\Users\...\project-root\node_modules\reshape-layouts\lib\index.js:16:12)
    at W.reduce (D:\Users\...\project-root\node_modules\reshape\lib\index.js:47:60)
    at tryCatchResolve (D:\Users\...\project-root\node_modules\when\lib\apply.js:46:23)
    at callAndResolve (D:\Users\...\project-root\node_modules\when\lib\apply.js:30:12) id: 'c08d682d'
}
Done in 13.77s.
```

**3. I modified `views/paper.sgr` as follow, and the error had been solved**

I added `views/` in front of `layout.sgr`.

```pug
extends(src='views/layout.sgr')
  block(name='content')
    h2 {{ item.title }}
```

This is not a fatal issue, but I'm curious whether this is an intended behavior. In my opinion, it would be better to find such imported files based on template file's location rather than the project root. It would be more consistent with other files in `views` folder.

Best regards,
Youngjae

**Comment by jescalan** [comment]
Yeah, this is true, you have certainly not been the first person to have been hit with this issue. Sorry about that! It's just about reference paths, I can patch this soon.

**Comment by yjcrocks** [comment]
Thanks for the kind reply. I should have checked the closed issues.

By the way, this is my first experience with the web development and I'm really enjoying it. Especially the convention you provided have helped me a lot! I really appreciate your hard work on the project. :)

**Comment by jescalan** [comment]
No worries, thanks for the clear issue! Honored to have been part of your first experience, and hope that it continues to work well for you! Just put in a patch for this issue which should be released in the next couple minutes 😁
