### ISSUE TITLE
using function as data

### ISSUE THREAD

**Issue by garywu** [static-dev/spike-records#76]
I'm using a thirdparty api to provide data in the records.  None of the existing methods seem to fit this use case. 
I added a line to allow a function as data in the run function
```
    if (this.opts[k].cb) { tasks[k] = this.opts[k].cb() }
```
then I just construct my record like this:
```
new Records({
    apidata: { cb: function_to_call_api_then_return_data_as_promise },
    ...
}
```

This seems to be cleaner than getting the data separately and then construct the record.

**Comment by jescalan** [comment]
Seems good to me, want to PR it?
